# Generated by Django 5.2.8 on 2025-11-10 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_of_article", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("image", models.CharField(blank=True, max_length=300)),
            ],
        ),
    ]
