# Generated by Django 5.2.8 on 2025-11-10 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="name_of_article",
            new_name="title",
        ),
    ]
